export const data = {
  categories: [
    {
      name: 'Appetizers',
      code: 'appetizers',
      slug: 'appetizers',
      icon: 'appetizers.svg',
      items: [
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Wild West Shrimp®',
          calorieCount: '970 - 1,200 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-wild-west-shrimp-dpv-8-21-18.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 11.49,
          indicators: [
            {
              iconName: 'LongHonn',
              tooltipText: 'Denotes LongHorn Steakhouse® Speciality',
            },
            {
              iconName: 'G',
              tooltipText: 'Denotes LongHorn Steakhouse® Speciality',
            },
          ],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'White Cheddar Stuffed Cheddar Stuffed',
          calorieCount: '780 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/WhtCdrStfMshr918x568.jpg',
          isDineInOnly: false,
          isFavourite: true,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Spicy Chicken Bites',
          calorieCount: '450 - 870 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/spicy-chicken-bites-918x568-dpv.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Texas Tonion®',
          calorieCount: '900 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-texas-tonion-dpv-11-21-17.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Firecracker Chicken Wraps',
          calorieCount: '970 - 1,200 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-firecracker-chicken-wraps-dpv-4-4-17.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 10.49,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Seasoned Steakhouse Wings',
          calorieCount: '560 - 980 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/seasoned-steakhouse-wings-d-20191119-dpv.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 11.29,
          indicators: [],
        },
      ],
    },
    {
      name: 'Legendary Steaks & COMBOS',
      code: 'legendary-steaks-and-combos',
      slug: 'legendary-steaks-and-combos',
      icon: 'steak.svg',
      subCategories: [
        {
          name: 'Legendary Steaks',
          code: 'legendary-steaks',
          slug: 'legendary-steaks',
          icon: 'steak.svg',
          items: [
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: "Flo's Filet®",
              calorieCount: '450 - 870 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/flos-filet-d-20191119-dpv.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: true,
              isUnavailable: false,
              price: 22.29,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Outlaw Ribeye®*',
              calorieCount: '700 - 1,250 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/outlaw-ribeye-d-20190224-dpv.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 27.79,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Renegade Sirloin',
              calorieCount: '970 - 1,200 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/1578LH_6ozSirloinSzleRGB_918x568.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: true,
              isSuggested: false,
              isUnavailable: true,
              price: 13.79,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Fire-Grilled T-Bone*',
              calorieCount: '700 - 1,250 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/fire-grilled-t-bone-d-20190224-dpv.jpg',
              isDineInOnly: true,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 27.79,
              indicators: [],
            },
          ],
        },
        {
          name: 'Grill Master Combos',
          code: 'grill-master-combos',
          slug: 'grill-master-combos',
          icon: 'steak.svg',
          items: [
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Renegade Sirloin* & Redrock Grilled Shrimp',
              calorieCount: '1,370 - 1,800  cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/sirloin-redrock-shrimp-918x568-dpv.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 19.79,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: "Flo's Filet®* & Maine Lobster Tail",
              calorieCount: '1,160 - 2,180 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/1467LH_FloFltLbstrTailRGB_918x568.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 30.49,
              indicators: [],
            },
          ],
        },
      ],
    },
    {
      name: 'Chicken, Seafood and More',
      code: 'chicken-seafood-and-more',
      slug: 'chicken-seafood-and-more',
      icon: 'appetizers.svg',
      items: [
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Wild West Shrimp®',
          calorieCount: '970 - 1,200 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-wild-west-shrimp-dpv-8-21-18.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 11.49,
          indicators: [
            {
              iconName: 'LongHonn',
              tooltipText: 'Denotes LongHorn Steakhouse® Speciality',
            },
            {
              iconName: 'G',
              tooltipText: 'Denotes LongHorn Steakhouse® Speciality',
            },
          ],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'White Cheddar Stuffed Cheddar Stuffed',
          calorieCount: '780 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/WhtCdrStfMshr918x568.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Spicy Chicken Bites',
          calorieCount: '450 - 870 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/spicy-chicken-bites-918x568-dpv.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Texas Tonion®',
          calorieCount: '900 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-texas-tonion-dpv-11-21-17.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Firecracker Chicken Wraps',
          calorieCount: '970 - 1,200 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-firecracker-chicken-wraps-dpv-4-4-17.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 10.49,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Seasoned Steakhouse Wings',
          calorieCount: '560 - 980 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/seasoned-steakhouse-wings-d-20191119-dpv.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 11.29,
          indicators: [],
        },
      ],
    },
    {
      name: 'Entree salads',
      code: 'entree-salads',
      slug: 'entree-salads',
      icon: 'steak.svg',
      subCategories: [
        {
          name: 'Legendary Steaks',
          code: 'legendary-steaks',
          slug: 'legendary-steaks',
          icon: 'steak.svg',
          items: [
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: "Flo's Filet®",
              calorieCount: '450 - 870 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/flos-filet-d-20191119-dpv.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: true,
              isUnavailable: false,
              price: 22.29,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Outlaw Ribeye®*',
              calorieCount: '700 - 1,250 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/outlaw-ribeye-d-20190224-dpv.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 27.79,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Renegade Sirloin',
              calorieCount: '970 - 1,200 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/1578LH_6ozSirloinSzleRGB_918x568.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: true,
              isSuggested: false,
              isUnavailable: true,
              price: 13.79,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Fire-Grilled T-Bone*',
              calorieCount: '700 - 1,250 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/fire-grilled-t-bone-d-20190224-dpv.jpg',
              isDineInOnly: true,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 27.79,
              indicators: [],
            },
          ],
        },
        {
          name: 'Grill Master Combos',
          code: 'grill-master-combos',
          slug: 'grill-master-combos',
          icon: 'steak.svg',
          items: [
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Renegade Sirloin* & Redrock Grilled Shrimp',
              calorieCount: '1,370 - 1,800  cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/sirloin-redrock-shrimp-918x568-dpv.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 19.79,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: "Flo's Filet®* & Maine Lobster Tail",
              calorieCount: '1,160 - 2,180 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/1467LH_FloFltLbstrTailRGB_918x568.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 30.49,
              indicators: [],
            },
          ],
        },
      ],
    },
    {
      name: 'Sides, salads and soups',
      code: 'sides-salads-and-soups',
      slug: 'sides-salads-and-soups',
      icon: 'appetizers.svg',
      items: [
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Wild West Shrimp®',
          calorieCount: '970 - 1,200 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-wild-west-shrimp-dpv-8-21-18.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 11.49,
          indicators: [
            {
              iconName: 'LongHonn',
              tooltipText: 'Denotes LongHorn Steakhouse® Speciality',
            },
            {
              iconName: 'G',
              tooltipText: 'Denotes LongHorn Steakhouse® Speciality',
            },
          ],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'White Cheddar Stuffed Cheddar Stuffed',
          calorieCount: '780 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/WhtCdrStfMshr918x568.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Spicy Chicken Bites',
          calorieCount: '450 - 870 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/spicy-chicken-bites-918x568-dpv.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Texas Tonion®',
          calorieCount: '900 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-texas-tonion-dpv-11-21-17.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Firecracker Chicken Wraps',
          calorieCount: '970 - 1,200 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-firecracker-chicken-wraps-dpv-4-4-17.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 10.49,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Seasoned Steakhouse Wings',
          calorieCount: '560 - 980 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/seasoned-steakhouse-wings-d-20191119-dpv.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 11.29,
          indicators: [],
        },
      ],
    },
    {
      name: 'Lunch (Mon-Sat 11-3pm)',
      code: 'lunch-mon-sat-11-3pm',
      slug: 'lunch-mon-sat-11-3pm',
      icon: 'steak.svg',
      // time: "Mon - Sat : 11 AM - 3 PM",
      subCategories: [
        {
          name: 'Legendary Steaks',
          code: 'legendary-steaks',
          slug: 'legendary-steaks',
          icon: 'steak.svg',
          items: [
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: "Flo's Filet®",
              calorieCount: '450 - 870 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/flos-filet-d-20191119-dpv.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: true,
              isUnavailable: false,
              price: 22.29,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Outlaw Ribeye®*',
              calorieCount: '700 - 1,250 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/outlaw-ribeye-d-20190224-dpv.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 27.79,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Renegade Sirloin',
              calorieCount: '970 - 1,200 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/1578LH_6ozSirloinSzleRGB_918x568.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: true,
              isSuggested: false,
              isUnavailable: true,
              price: 13.79,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Fire-Grilled T-Bone*',
              calorieCount: '700 - 1,250 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/fire-grilled-t-bone-d-20190224-dpv.jpg',
              isDineInOnly: true,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 27.79,
              indicators: [],
            },
          ],
        },
        {
          name: 'Grill Master Combos',
          code: 'grill-master-combos',
          slug: 'grill-master-combos',
          icon: 'steak.svg',
          items: [
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Renegade Sirloin* & Redrock Grilled Shrimp',
              calorieCount: '1,370 - 1,800  cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/sirloin-redrock-shrimp-918x568-dpv.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 19.79,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: "Flo's Filet®* & Maine Lobster Tail",
              calorieCount: '1,160 - 2,180 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/1467LH_FloFltLbstrTailRGB_918x568.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 30.49,
              indicators: [],
            },
          ],
        },
      ],
    },
    {
      name: 'Desserts',
      code: 'desserts',
      slug: 'desserts',
      icon: 'appetizers.svg',
      items: [
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Wild West Shrimp®',
          calorieCount: '970 - 1,200 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-wild-west-shrimp-dpv-8-21-18.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 11.49,
          indicators: [
            {
              iconName: 'LongHonn',
              tooltipText: 'Denotes LongHorn Steakhouse® Speciality',
            },
            {
              iconName: 'G',
              tooltipText: 'Denotes LongHorn Steakhouse® Speciality',
            },
          ],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'White Cheddar Stuffed Cheddar Stuffed',
          calorieCount: '780 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/WhtCdrStfMshr918x568.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Spicy Chicken Bites',
          calorieCount: '450 - 870 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/spicy-chicken-bites-918x568-dpv.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Texas Tonion®',
          calorieCount: '900 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-texas-tonion-dpv-11-21-17.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Firecracker Chicken Wraps',
          calorieCount: '970 - 1,200 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-firecracker-chicken-wraps-dpv-4-4-17.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 10.49,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Seasoned Steakhouse Wings',
          calorieCount: '560 - 980 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/seasoned-steakhouse-wings-d-20191119-dpv.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 11.29,
          indicators: [],
        },
      ],
    },
    {
      name: 'Kids',
      code: 'kids',
      slug: 'kids',
      icon: 'steak.svg',
      subCategories: [
        {
          name: 'Legendary Steaks',
          code: 'legendary-steaks',
          slug: 'legendary-steaks',
          icon: 'steak.svg',
          items: [
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: "Flo's Filet®",
              calorieCount: '450 - 870 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/flos-filet-d-20191119-dpv.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: true,
              isUnavailable: false,
              price: 22.29,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Outlaw Ribeye®*',
              calorieCount: '700 - 1,250 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/outlaw-ribeye-d-20190224-dpv.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 27.79,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Renegade Sirloin',
              calorieCount: '970 - 1,200 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/1578LH_6ozSirloinSzleRGB_918x568.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: true,
              isSuggested: false,
              isUnavailable: true,
              price: 13.79,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Fire-Grilled T-Bone*',
              calorieCount: '700 - 1,250 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/fire-grilled-t-bone-d-20190224-dpv.jpg',
              isDineInOnly: true,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 27.79,
              indicators: [],
            },
          ],
        },
        {
          name: 'Grill Master Combos',
          code: 'grill-master-combos',
          slug: 'grill-master-combos',
          icon: 'steak.svg',
          items: [
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: 'Renegade Sirloin* & Redrock Grilled Shrimp',
              calorieCount: '1,370 - 1,800  cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/sirloin-redrock-shrimp-918x568-dpv.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 19.79,
              indicators: [],
            },
            {
              id: 'abc',
              code: 'abc',
              isComplex: false,
              name: "Flo's Filet®* & Maine Lobster Tail",
              calorieCount: '1,160 - 2,180 cal',
              imageUrl:
                'https://media.longhornsteakhouse.com/en_us/images/product/1467LH_FloFltLbstrTailRGB_918x568.jpg',
              isDineInOnly: false,
              isFavourite: false,
              isNew: false,
              isSuggested: false,
              isUnavailable: false,
              price: 30.49,
              indicators: [],
            },
          ],
        },
      ],
    },
    {
      name: 'Steakhouse Drinks and Beverages',
      code: 'steakhouse-drinks-and-beverages',
      slug: 'steakhouse-drinks-and-beverages',
      icon: 'appetizers.svg',
      items: [
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Wild West Shrimp®',
          calorieCount: '970 - 1,200 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-wild-west-shrimp-dpv-8-21-18.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 11.49,
          indicators: [
            {
              iconName: 'LongHonn',
              tooltipText: 'Denotes LongHorn Steakhouse® Speciality',
            },
            {
              iconName: 'G',
              tooltipText: 'Denotes LongHorn Steakhouse® Speciality',
            },
          ],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'White Cheddar Stuffed Cheddar Stuffed',
          calorieCount: '780 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/WhtCdrStfMshr918x568.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Spicy Chicken Bites',
          calorieCount: '450 - 870 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/spicy-chicken-bites-918x568-dpv.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Texas Tonion®',
          calorieCount: '900 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-texas-tonion-dpv-11-21-17.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 8.99,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Firecracker Chicken Wraps',
          calorieCount: '970 - 1,200 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/d-firecracker-chicken-wraps-dpv-4-4-17.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 10.49,
          indicators: [],
        },
        {
          id: 'abc',
          code: 'abc',
          isComplex: false,
          name: 'Seasoned Steakhouse Wings',
          calorieCount: '560 - 980 cal',
          imageUrl:
            'https://media.longhornsteakhouse.com/en_us/images/product/seasoned-steakhouse-wings-d-20191119-dpv.jpg',
          isDineInOnly: false,
          isFavourite: false,
          isNew: false,
          isSuggested: false,
          isUnavailable: false,
          price: 11.29,
          indicators: [],
        },
      ],
    },
  ],
};
